In [3]:
# import the basic packages for the problem
# no fancy packages.
import numpy as np
from sklearn import tree

In [4]:
# fix the seed
np.random.seed(1)
## generate the dataset
# the dimension and size of the data
p = 10
n_train = 2000
n_test = 200


# two distribution we sample data from
mu1 = np.repeat(0.5,p)
sigma1 = np.eye(p)
mu2 = np.repeat(-0.5,p)
sigma2 = np.eye(p)

# construct the training dataset
train_x1 = np.random.multivariate_normal(mu1,sigma1,n_train)
train_y1 = np.repeat(1,n_train)

train_x2 = np.random.multivariate_normal(mu2,sigma2,n_train)
train_y2 = np.repeat(-1,n_train)

train_x = np.vstack((train_x1,train_x2))
train_y = np.hstack((train_y1,train_y2))

print('the size of the training dataset is:',train_x.shape)
print(train_y.shape)

# constructing the testing dataset
test_x1 = np.random.multivariate_normal(mu1,sigma1,n_test)
test_y1 = np.repeat(1,n_test)

test_x2 = np.random.multivariate_normal(mu2,sigma2,n_test)
test_y2 = np.repeat(-1,n_test)

test_x = np.vstack((test_x1,test_x2))
test_y = np.hstack((test_y1,test_y2))

print('the size of the testing dataset is:',test_x.shape)
print(test_y.shape)


the size of the training dataset is: (4000, 10)
(4000,)
the size of the testing dataset is: (400, 10)
(400,)


In [5]:
element = np.unique(train_y)
K = len(element)
print(element,K)

[-1  1] 2


In [11]:
# Here I define a class as an agent to do
# Gradient Boosting for K-Class Classification
class K_GBoost():
    def __init__(self,X,y,M,init,element):
        # Input:
        # X: X train matrix dimention: n by d
        # y: y train: n by 1
        # M: integer, the loop number
        # init: initial f vector: K by 1
        self.X = X
        self.y = y
        self.Max_iter = M
        self.init = init
        self.K = len(element)
        self.element = element
        
        
    @staticmethod 
    # this function is weighted sum
    def f_val(f_set, X):
        f = 0
        for i in range(len(f_set)):
            if i == 0:
                f += f_set[i](X)
            else:
                # make sure the return is column vector
                f += f_set[i].predict(X).reshape(-1,1)
        return f
    
    @staticmethod
    # this method is aimed to 
    def p(f):
        return np.exp(f) / sum(np.exp(f))
    
    @staticmethod
    # this funtion is aimed to convert the y vector
    # into the indicator vector
    def y_indicator(y, k, element):
        targat = element[k]
#         print(y.shape)
        index = y == targat
#         print(len(index))
        y[index] = 1
        rev = np.array([not i for i in index]).reshape(-1,)
#         print(rev.shape)
        y[rev] = -1

        
        return y
    
    def fit(self):
        # initial the f
        f = self.init
        # f_set is a collection of classifier
        f_set = list()
        # add the init classifier to the f_set, return 0 column
        f_set.append(lambda X: np.zeros(X.shape[0]).reshape(-1,1))
        
        for i in range(self.Max_iter):
            f = self.f_val(f_set, self.X)
            # set p_k
            p = self.p(f)
            
            for k in range(self.K):
                print(k)
                y_k = self.y_indicator(self.y, k, self.element)
                r = y_k - p
                print(r)
                self.reg_tree = tree.DecisionTreeRegressor()
                self.reg_tree = self.reg_tree.fit(self.X, r)
                print(self.reg_tree.apply(self.X))
#     def predict(self,X):
        

In [12]:
if __name__ == '__main__':
    init = np.zeros(K).reshape(-1,1)
    GBoost = K_GBoost(train_x,train_y,2,init,element)
    model = GBoost.fit()
    tree_1 = GBoost.reg_tree

0
[[-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 ...
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]]
[0 0 0 ... 0 0 0]
1
[[-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 ...
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]
 [-1.00025 -1.00025 -1.00025 ...  0.99975  0.99975  0.99975]]
[0 0 0 ... 0 0 0]
0
[[ 0.99975  0.99975  0.99975 ... -1.00025 -1.00025 -1.00025]
 [ 0.99975  0.99975  0.99975 ... -1.00025 -1.00025 -1.00025]
 [ 0.99975  0.99975  0.99975 ... -1.00025 -1.00025 -1.00025]
 ...
 [ 0.99975  0.99975  0.999

In [10]:
sum(tree_1.apply(train_x)==0)

4000

In [21]:
X = np.array([[1,3,4],[2,5,6]])
print(X)
print(X.shape[1])
z = np.zeros(3).reshape(-1,1)
print(z[1])
a = np.array([1,2,3]).reshape(-1,1)
print(a)
print(np.exp(a))


[[1 3 4]
 [2 5 6]]
3
[0.]
[[1]
 [2]
 [3]]
[[ 2.71828183]
 [ 7.3890561 ]
 [20.08553692]]


TypeError: 'int' object is not subscriptable

In [2]:
X = [[0, 0,0], [2, 2,2]]
y = [0.5, 2.5]
clf1 = tree.DecisionTreeRegressor()
clf1 = clf1.fit(X, y)
print(clf1.predict([[1, 1,1]]))

clf2 = tree.DecisionTreeRegressor()
clf2 = clf2.fit(X, y)
print(clf2.predict([[1, 1,1],[1,1,1]]).reshape(-1,1))

clf = list()
clf.append(clf1)
clf.append(clf2)
a  = clf[0].predict([[1,1,1]])
print(a)


print()

[0.5]
[[0.5]
 [0.5]]
[0.5]



In [51]:
f_set = list()
f_set.append(lambda X: np.zeros(X.shape[0]).reshape(-1,1))
print(f_set[0](np.array([[1,2,3],[2,3,4]])))

[[0.]
 [0.]]


In [3]:
train_y

array([ 1,  1,  1, ..., -1, -1, -1])

In [33]:
a = np.array([1,1,1,-1,-1,-1,1]).reshape(-1,1)
print(a)
index = a == 1
print(index)
a[index] = 1
print(a)
rev = np.array([not i for i in index]).reshape(-1,1)
print(rev)
a[rev] = -1
print(a)

[[ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [ 1]]
[[ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]]
[[ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [ 1]]
[[False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]]
[[ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [ 1]]


In [53]:
range(3)
for i in range(2):
    print(i)
print(range(3))

0
1
range(0, 3)
